готовый проект
ValyGer/java-filmorate pull request #1
Opened 2023-12-06 10:14 UTC by ValyGer

2023-12-06 15:56 UTC, andrew-larkin requested changes
Привет! Отличный старт! реализация очень качественная и тесты хорошо написаны. В самих тестах остается добавить пару методов и по коду чисто косметические правки.

2023-12-06 15:56 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +    FilmValidation filmValidation = new FilmValidation();
модификаторы доступа тоже добавляем в тесты - приватные, если от тестового класса никто не наследуется. для юзеров то же самое

2023-12-06 15:56 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/validation/UserValidationTest.java
> +    UserController userController = new UserController();
тут стоит и другие методы контроллера протестировать

2023-12-06 15:56 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +
методы контроллера тоже можно здесь протестировать

2023-12-10 16:09 UTC, ValyGer commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +    public void validateFilm(Film film) {
Откорректировал

2023-12-10 16:12 UTC, ValyGer commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +    FilmValidation filmValidation = new FilmValidation();
В тестовых классах получается поставить только модификатор public и package-private. Приватными сделать не получилось, IDEA ошибку выдает.

2023-12-10 20:57 UTC, ValyGer commented on src/test/java/ru/yandex/practicum/filmorate/validation/UserValidationTest.java
> +    UserController userController = new UserController();
Добавил тесты

2023-12-10 20:57 UTC, ValyGer commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +
добавил тесты

2023-12-11 09:46 UTC, merged