Add friends likes
ValyGer/java-filmorate pull request #2
Opened 2023-12-20 10:16 UTC by ValyGer

Изменена архитектура приложения. Доработка приложения по части работы со списками друзей и проставлением лайков фильмам.

2023-12-20 23:26 UTC, andrew-larkin requested changes
Привет! Очень хорошо, реализован новый функционал, код чистый, хорошие решения применены. Остается покрыть тестами новые методы, а также внести небольшие корректировки в контроллеры и работа будет принята.

2023-12-20 23:26 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@AllArgsConstructor
можно использовать @RequiredArgsConstructor - тогда поля помеченные final будут автоматически добавляться в неявный конструктор

2023-12-20 23:26 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmService filmService;
внедряемые зависимости лучше обозначать как final - это значит, что инициализация объекта произойдет гарантировано один раз - что нам и требуется

2023-12-20 23:26 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@AllArgsConstructor
аналогично FilmController

2023-12-20 23:26 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +@AllArgsConstructor
тут такая же схема как и в контроллере. логгирование можно оставить как есть

2023-12-20 23:26 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +    InMemoryFilmStorage inMemoryFilmStorage = new InMemoryFilmStorage();
в тестовых классах тоже стоит использовать модификаторы доступа, в данном случае, приватные

2023-12-20 23:26 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +public class FilmValidationTest {
тут стоит добавить тесты на новые методы контроллера. здесь и в тестовом классе для юзера

2023-12-28 17:54 UTC, ValyGer commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@AllArgsConstructor
Откорректировал

2023-12-28 17:55 UTC, ValyGer commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmService filmService;
Откорректировал

2023-12-28 17:55 UTC, ValyGer commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@AllArgsConstructor
Откорректировал

2023-12-28 17:55 UTC, ValyGer commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +@AllArgsConstructor
Откорректировал

2023-12-28 17:56 UTC, ValyGer commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +    InMemoryFilmStorage inMemoryFilmStorage = new InMemoryFilmStorage();
Добавил модификаторы доступа

2023-12-28 17:56 UTC, ValyGer commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +public class FilmValidationTest {
Добавил тесты для контроллеров фильмов и юзеров.

2023-12-28 21:11 UTC, merged